### ISSUE TITLE
Correct bill orientation with EXIF entry

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#148]
Some bills are displayed and processed sideways, especially when they are recorded with a mobile phone camera. In many cases, these images contain an EXIF entry indicating the orientation, though.

An example is bill gCQ76uE6qLYhEdsY9.JPG. When you open it with on your computer, it will get displayed correctly since the viewer app will consider the orientation EXIF entry. RMagick also gives us the possibility to use this tag: https://rmagick.github.io/image1.html#auto_orient_bang

Let's use it!

Also we can access this EXIF entry  in RMagick with [get_exif_by_entry](https://rmagick.github.io/image2.html#get_exif_by_entry). This entry is called `Orientation`. More info on this EXIF entry: https://beradrian.wordpress.com/2008/11/14/rotate-exif-images/
Please include the orientation in the recognition result in a meaningful format so we can also display the bill with corrected orientation to the reviewer.

**Comment by tamacodechi** [comment]
What kind of meaningful format could we use?
```
0 degrees clockwise = Orientation: 1 = 0
90 degrees clockwise = Orientation: 6 = 1
180 degrees clockwise = Orientation: 3 = 2
270 degrees clockwise = Orientation: 8 = 3
```
Is fine but how can we account for for orientations 2, 4, 5, and 7, all of which require flipping and possibly even rotating? Would a hash with clockwise rotation, horizontal rotation, and vertical rotation be better? 

Personally I think passing the exif data and collaborating with whoever builds it would be better since passing a number we assign as a value in the recogniser and then translating that to code in the web app is two translations 
`exif entry --> number of rotations --> code that will carry out rotations in the web app`
 whereas if we pass the exif entry to the web app it would be a direct translation from
 `exif entry --> code that will carry out rotations` 

Unless the code we apply in the web app will just be a simple _"rotate by orientation.X times 90 and flip horizontally orientation.Y times and flip vertically orientation.Z times"_ in which case I'm overthinking it and it should indeed be in the recognizer 😅

**Comment by clemenshelm** [comment]
I don't think cases dealing with flipping the image exist for our use case. At least I've never encountered one. So I'm quite sure rotating will be enough.

**Comment by tamacodechi** [comment]
Okay perfect, that's what I've implemented so far anyway 😉

**Comment by clemenshelm** [comment]
Just to be precise: What does rotation `1` mean? Does it mean

- The bill *is* rotated 90 degrees clockwise or
- the bill *needs to be* rotated 90 degrees clockwise

These are kind of the opposite things 😄

**Comment by tamacodechi** [comment]
Needs to be. Should I name the attribute to be something more descriptive like `rotationsRequired` instead of `orientation`?

**Comment by clemenshelm** [comment]
Yes, this would be great!

**Comment by clemenshelm** [comment]
Or even `clockwiseRotationsRequired`.
