### ISSUE TITLE
GBP detected when EUR was main currency

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#173]
In bill `6rYBRincCdkNbCeRB.pdf` GBP was detected as main currency because there is one £ symbol on the bill. Still, it's clearly recognizable that the main currency of the bill is EUR.

**Comment by tamacodechi** [comment]
Maybe this can be fixed by making the currency calculation more clever. For example the invoice date calculation takes the first standalone date, and if that doesn't work the first labelled date and if that doesn't work the "from" date from the billing period.

So, you could make something that is more accurate than just ```.last``` like searching for a currency term that is ```.right_after``` the price term that is the total amount on the bill. 

So you can have ``` most accurate case || .last case ``` to be set as the currency.

If you use ```.right_after``` you need to include dimensionable and the syntax would be 
```<type of term to find>.right_after(<the thing that should be preceeding it>) ```

eg. 
```DateTerm.right_after(BillingStartLabelTerm.first) ``` will find the date term that is right after the first billing period start label, if there is one.
