### ISSUE TITLE
Lint Ruby

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#23]

**Comment by tamacodechi** [comment]
### Update:

I'm done with an [older version](https://github.com/clemenshelm/chillbill-recognizer/commit/c262cf7b18e3aa5d9f17681f31a5a514f1aeb7ac):
`47 files inspected, no offenses detected` 

I had started this before the PR for #21 was done reviewing, so I'll leave this as is until #21 and #22  gets merged, and then pull in the changes - then leave the _alllllll the code base pretty_ ✨  
I'd like to add rubocop to the CI (but I think that's part of #26 ) so that it'll yell at us for sure if there are syntax errors (I mean we should all be running it anyway before doing PRs but we're all human here, right? ಠ_ಠ  ... Right?) and at least throw warnings for other bad things we do.

**Comment by tamacodechi** [comment]
Can/Should I add a couple of lines on rubocop to the read me in case anyone who joins in dev of the recognizer who isn't familiar with it (esp. the other cops) can just find info there?

_Sorry for all the comments, testing is slow._ ʱªʱªʱª (ᕑᗢूᓫ∗)

**Comment by clemenshelm** [comment]
Would be nice :)
