### ISSUE TITLE
Don't trim bills, use text boundaries instead

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#310]
Trimming bills doesn't work reliably: Sometimes the bill is not trimmed sufficiently because of single black pixels, sometimes too much is trimmed (logos, light fonts).

Instead of trimming we want to use two boxes instead:

- The total width and height (bill dimensions) and
- the text box

The text box is the bounding box of all words of a bill page, so the minimum left and top and the maximum right and bottom coordinate of all words.

Relative word coordinates should be calculated from the bill dimensions, not from the text box (probably requires no changes). We can still calculate coordinates relative to the text box  later on if we need them.

Pass both the bill dimensions and the text box to machine learning.

**Comment by tamacodechi** [comment]
Do we want to filter out non character words? With something like tables, I think that's still text on the page that should be taken into account with the text box shouldn't it? 

With the new version of tesseract I have not encountered any "reading" of smudges or tables as characters.

Just wondering because it's not written up on the issue ;)

**Comment by clemenshelm** [comment]
Yes, but only if you find some. Don't assume something which isn't there, we can still take care of special cases later on.
