### ISSUE TITLE
missing prices

### ISSUE THREAD

**Issue by Thomas1e** [clemenshelm/chillbill-recognizer#333]
- In the bill 2BWLcAHqKAJTzwSDC.jpg a lot of prices are not in detected and therefore are missing in the yml file.

Prices that are detected: 5.34;  0.49;   4.85;  300

![bildschirmfoto vom 2017-08-08 16-22-26](https://user-images.githubusercontent.com/26839274/29077370-3eb741c4-7c58-11e7-80ae-55ea6ac6e100.png)

- In fRN7LRFs8ZRyyeFdE.pdf the MwSt value was not detected, but it should be.

- In FvK6uW7F9A62f4YGZ.pdf the value "41.02" should be detected 4 times, but was only detected twice.

- In C5sri9hxpbDhha68D.png the value "23,55" should be detected 2 times, but was not detected

- In rDxLnivxoXQw9nWa7.pdf the values "431.25" and "86.25" are not detecetd

- In LcW5EsYpEX7FTsUF3.jpg the value "8.29" is missing

**Comment by Tr4in** [comment]
2BWLcAHqKAJTzwSDC.jpg:
![selection_002](https://user-images.githubusercontent.com/21169462/29577846-412515ba-876d-11e7-8175-04b1ff9e26e8.png)

fRN7LRFs8ZRyyeFdE.pdf:
![selection_003](https://user-images.githubusercontent.com/21169462/29577904-7fe09612-876d-11e7-9126-4cde95ccc058.png)

FvK6uW7F9A62f4YGZ.pdf:
41,02* got recognized but not valid! The other one is OCR

C5sri9hxpbDhha68D.png:
23,55 is OCR. 21,41 should be removed because Mwst.

rDxLnivxoXQw9nWa7.pdf:
Really weird! Valid but not recognized
![selection_004](https://user-images.githubusercontent.com/21169462/29578612-1d8f8ce0-8770-11e7-9fba-347b69342d83.png)


LcW5EsYpEX7FTsUF3.jpg:
![selection_005](https://user-images.githubusercontent.com/21169462/29578586-0877f428-8770-11e7-90b5-1f8e9a9ae919.png)
