### ISSUE TITLE
"Zahlungsziel" as due date

### ISSUE THREAD

**Issue by clemenshelm** [clemenshelm/chillbill-recognizer#59]
The due date of the following bills is referred to as "Zahlungsziel" and is not recognized correctly:

- fGHCBxN6cbksNrHpo: 2016-10-04 instead of 2016-10-18
- egh8L5rsTxe2hH2vz: 2016-10-31 instead of 2016-11-14
- LETxtvFjWDKmH7Gqq: 2016-10-31 instead of 2016-11-30
- 3Xsz6DWNbJJ3xtWaJ: 2016-10-31 instead of 2016-11-14
- kiKppj24YPr4m5WaD: 2016-10-07 instead of 2016-11-20
- DdTQkLG76vaYumzvh: 2016-10-31 instead of 2016-11-14
- ShqNCy4YvnHH5A96j: 2016-10-07 instead of 2016-11-20

**Comment by tamacodechi** [comment]
@clemenshelm Are all of these PDFs? In order to fetch the tests we also need the extension 😉 

**WIP:**
- [x] fGHCBxN6cbksNrHpo: 2016-10-04 instead of 2016-10-18
- [x] egh8L5rsTxe2hH2vz: 2016-10-31 instead of 2016-11-14
- [x] LETxtvFjWDKmH7Gqq: 2016-10-31 instead of 2016-11-30
- [x] 3Xsz6DWNbJJ3xtWaJ: 2016-10-31 instead of 2016-11-14
- [x] kiKppj24YPr4m5WaD: 2016-10-07 instead of 2016-11-20
- [x] DdTQkLG76vaYumzvh: 2016-10-31 instead of 2016-11-14
- [x] ShqNCy4YvnHH5A96j: 2016-10-07 instead of 2016-11-20
